### PR TITLE
WIP: ✨Add standalone Course Creator

### PR DESCRIPTION
**Pull request by vikaspotluri123**
refs gradebook/engineering#61
This is _very_ WIP! Wanted to get some first impressions though.

To preview:

1. Pull latest version of Course Creator
1. `yarn build` to get a release version of Course Creator
1. Pull this branch
1. `yarn link @gradebook/course-creator`
1. yarn dev
1. Navigate to `/create-course/` (route tbd)

### CODE REVIEW

**Comment by joshcosta** [comment]
Initial impressions:
- Cool school selector! We could look into doing the background change in the sign-up flow as well.
- Blur effect is super good looking but we need to improve contrast and make sure the strategy works for a variety of backgrounds
- I think we need to incorporate the header and footer. Might clash with the theming so we'll have to look at that.

**Comment by vikaspotluri123** [comment]
> Blur effect is super good looking but we need to improve contrast and make sure the strategy works for a variety of backgrounds

I changed the background to white with 20% opacity. What do you think?

**Comment by joshcosta** [comment]
Looks good. I think the selector and button should be styled simalar-ly

**Comment by vikaspotluri123** [comment]
closing for now, will reopen when this is reprioritized.

**Pull request closed without merging**
